"""Verify trajectories by their reactions: turns, the next-state judge, and
the RLM-proposed checks that anchor to it."""

from bandits.verify.judge import (
    DEFAULT_MODEL as JUDGE_DEFAULT_MODEL,
)
from bandits.verify.judge import (
    Completion,
    JudgeError,
    fireworks_completion,
    render_transcript,
    resolve_api_key,
)
from bandits.verify.nextstate import (
    ARCHETYPE_VOCABULARY,
    Archetype,
    TurnJudgeRun,
    TurnVerdict,
    compute_judge_run_id,
    judge_turns,
    load_turn_judge_run,
    save_turn_judge_run,
)
from bandits.verify.propose import (
    CheckStats,
    FamilyCheck,
    FamilyVerifier,
    FlaggedTurn,
    ProposalError,
    ProposedCheck,
    RejectedCheck,
    TraceScore,
    VerifierScores,
    apply_verifier,
    compile_check,
    compute_scores_id,
    compute_verifier_id,
    decide_check,
    evaluate_check,
    load_family_verifier,
    load_verifier_scores,
    propose_verifier,
    revise_check,
    run_check,
    save_family_verifier,
    save_verifier_scores,
    survival,
)
from bandits.verify.turns import Turn, extract_turns, render_action

__all__ = [
    "ARCHETYPE_VOCABULARY",
    "Archetype",
    "Completion",
    "JUDGE_DEFAULT_MODEL",
    "JudgeError",
    "TurnJudgeRun",
    "TurnVerdict",
    "compute_judge_run_id",
    "fireworks_completion",
    "judge_turns",
    "load_turn_judge_run",
    "render_transcript",
    "resolve_api_key",
    "save_turn_judge_run",
    "CheckStats",
    "FamilyCheck",
    "FamilyVerifier",
    "FlaggedTurn",
    "ProposalError",
    "ProposedCheck",
    "RejectedCheck",
    "TraceScore",
    "VerifierScores",
    "apply_verifier",
    "compile_check",
    "compute_scores_id",
    "compute_verifier_id",
    "decide_check",
    "evaluate_check",
    "load_family_verifier",
    "load_verifier_scores",
    "propose_verifier",
    "revise_check",
    "run_check",
    "save_family_verifier",
    "save_verifier_scores",
    "survival",
    "Turn",
    "extract_turns",
    "render_action",
]
