"""Deterministic analysis of a trace corpus: task candidates and outcome evidence.

Nothing here is inferred by a model. Every value is read directly off spans that
are already in the corpus, and anything the source did not record is named as a
limitation rather than filled in. Model-assisted analysis is a later, explicitly
labelled addition on top of this layer, never a replacement for it.
"""

from __future__ import annotations

from bandits.analyze.analysis import (
    analyze_corpus,
    compute_analysis_id,
    load_analysis,
    save_analysis,
)
from bandits.analyze.audit import (
    DEFAULT_MODEL as AUDIT_MODEL,
)
from bandits.analyze.audit import (
    AuditError,
    audit_family,
    audit_task_set,
    build_predictor,
    compute_audit_run_id,
    load_audit_run,
    save_audit_run,
)
from bandits.analyze.embed import (
    EmbeddingCache,
    EmbeddingError,
    build_cache,
    cosine_distance,
    embedding_distance,
    load_cache,
    save_cache,
)
from bandits.analyze.families import (
    DEFAULT_BUDGET,
    DEFAULT_DUPLICATE_SIMILARITY,
    DEFAULT_HELD_OUT,
    DEFAULT_NEIGHBORS,
    compute_task_set_id,
    fingerprint,
    load_task_set,
    merge_families,
    mine_task_set,
    normalize_instruction,
    normalize_request,
    save_task_set,
    split_family,
)
from bandits.analyze.models import (
    ClusteringProvenance,
    CorpusAnalysis,
    DuplicateEdge,
    Evidence,
    EvidenceKind,
    FamilyAudit,
    FamilyAuditRun,
    LeakageError,
    MissingSlot,
    SelectedTask,
    SkippedAudit,
    SlotKind,
    TaskCandidate,
    TaskFamily,
    TaskSet,
    Visibility,
    build_task_candidate,
)
from bandits.analyze.outcomes import extract_outcome_evidence
from bandits.analyze.rlm_assign import (
    AssignmentError,
    assign_traces,
    compute_assignment_run_id,
    load_assignment_run,
    save_assignment_run,
)
from bandits.analyze.rlm_audit import (
    FreezeRefused,
    TaxonomyAuditError,
    audit_taxonomy,
    compute_taxonomy_id,
    freeze_taxonomy,
    load_taxonomy,
    resolve_findings,
    save_taxonomy,
)
from bandits.analyze.rlm_audit import (
    compute_audit_id as compute_rlm_audit_id,
)
from bandits.analyze.rlm_audit import (
    load_audit as load_rlm_audit,
)
from bandits.analyze.rlm_audit import (
    save_audit as save_rlm_audit,
)
from bandits.analyze.rlm_corpus import ReadOnlyCorpus, build_view
from bandits.analyze.rlm_mine import (
    MiningError,
    compute_draft_id,
    load_draft,
    mine_taxonomy,
    save_draft,
)
from bandits.analyze.rlm_models import (
    AssignmentRun,
    AssignmentStatus,
    AuditFinding,
    Budget,
    ChunkResult,
    FamilyContract,
    FrozenTaxonomy,
    Operation,
    StopReason,
    TaxonomyAudit,
    TaxonomyDraft,
    TaxonomyOperation,
    TraceAssignment,
    TraceView,
    UserMessageView,
)
from bandits.analyze.rlm_stability import (
    PairDisagreement,
    StabilityReport,
    UnplacedTrace,
    compare_runs,
    compute_stability_report_id,
    load_stability_report,
    save_stability_report,
)
from bandits.analyze.rlm_taskset import MaterializationError, materialize_task_set
from bandits.analyze.tasks import extract_task

__all__ = [
    "AUDIT_MODEL",
    "AssignmentError",
    "AssignmentRun",
    "AssignmentStatus",
    "AuditError",
    "AuditFinding",
    "Budget",
    "ChunkResult",
    "ClusteringProvenance",
    "CorpusAnalysis",
    "DEFAULT_BUDGET",
    "DEFAULT_DUPLICATE_SIMILARITY",
    "DEFAULT_HELD_OUT",
    "DEFAULT_NEIGHBORS",
    "DuplicateEdge",
    "EmbeddingCache",
    "EmbeddingError",
    "Evidence",
    "EvidenceKind",
    "FamilyAudit",
    "FamilyAuditRun",
    "FamilyContract",
    "FreezeRefused",
    "FrozenTaxonomy",
    "LeakageError",
    "MaterializationError",
    "MiningError",
    "MissingSlot",
    "Operation",
    "PairDisagreement",
    "ReadOnlyCorpus",
    "SelectedTask",
    "SkippedAudit",
    "SlotKind",
    "StabilityReport",
    "StopReason",
    "TaskCandidate",
    "TaskFamily",
    "TaskSet",
    "TaxonomyAudit",
    "TaxonomyAuditError",
    "TaxonomyDraft",
    "TaxonomyOperation",
    "TraceAssignment",
    "TraceView",
    "UnplacedTrace",
    "UserMessageView",
    "Visibility",
    "analyze_corpus",
    "assign_traces",
    "audit_family",
    "audit_task_set",
    "audit_taxonomy",
    "build_cache",
    "build_predictor",
    "build_task_candidate",
    "build_view",
    "compare_runs",
    "compute_analysis_id",
    "compute_assignment_run_id",
    "compute_audit_run_id",
    "compute_draft_id",
    "compute_rlm_audit_id",
    "compute_stability_report_id",
    "compute_task_set_id",
    "compute_taxonomy_id",
    "cosine_distance",
    "embedding_distance",
    "extract_outcome_evidence",
    "extract_task",
    "fingerprint",
    "freeze_taxonomy",
    "load_analysis",
    "load_assignment_run",
    "load_audit_run",
    "load_cache",
    "load_draft",
    "load_rlm_audit",
    "load_stability_report",
    "load_task_set",
    "load_taxonomy",
    "materialize_task_set",
    "merge_families",
    "mine_task_set",
    "mine_taxonomy",
    "normalize_instruction",
    "normalize_request",
    "resolve_findings",
    "save_analysis",
    "save_assignment_run",
    "save_audit_run",
    "save_cache",
    "save_draft",
    "save_rlm_audit",
    "save_stability_report",
    "save_task_set",
    "save_taxonomy",
    "split_family",
]
