"""Contracts for the diagnose plane: scenarios, transitions, bindings, rollouts.

Three boundaries are enforced structurally here rather than by convention,
because each of them fails silently when it is left to discipline.

**Origin is not authority.** A fact's trust rank (``EvidenceKind``) answers how
directly it establishes an outcome; where it came from — a recorded production
run, an executable connector, or a learned simulator — is an independent
question. A simulated field can be perfectly authoritative about what happened
inside its own rollout branch while proving nothing about production. Collapsing
the two into one ordering loses that, and would also slip past
``VerifierSpec.rests_only_on_self_report``, which tests identity against one
enum member rather than comparing ranks. So ``WorldOrigin`` is carried beside the
authority, never folded into it.

**The candidate sees a strict subset.** A scenario holds the hidden user goal,
the sealed success contract, and the retrieval exclusions alongside the visible
task and prefix. Everything private is reachable only through accessors that say
so, and ``Scenario.candidate_view`` is the single function permitted to build
what a candidate is shown.

**Components are reported, never averaged.** Operational, process and
communication results are separate fields with their own authorities, and the
overall verdict fails closed when a required component is unknown.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import Field, model_validator

from bandits.analyze.models import EvidenceKind
from bandits.traces import Contract


class WorldOrigin(str, Enum):
    """Where a fact came from, independent of how much authority it carries.

    Deliberately not part of ``EvidenceKind``. See this module's docstring: a
    simulated terminal state may be the most authoritative thing available about
    a rollout branch and still be no evidence whatsoever about production.
    """

    RECORDED = "recorded"
    """Read off a real span in a real historical episode."""

    EXECUTABLE = "executable"
    """Produced by code and state we actually run. None today; Milestone 4."""

    SIMULATED = "simulated"
    """Generated by the learned world model. Never promotable, never reward."""


class SuccessShape(str, Enum):
    """What terminal success means for one task, structurally.

    A mined family groups tasks by what the user asked for, which is the right
    basis for retrieval and for workload mass. It is *not* a promise that the
    tasks share an outcome shape: the target family holds pure refusals, one
    booking mutation, read-only lookups and a compound cancel-and-rebook. One
    fixed terminal shape cannot honestly verify all four, and forcing them into
    the nearest tag is how a refusal task starts reporting an operational pass.
    """

    REFUSAL = "refusal"
    """Success is that specified writes did *not* happen, plus what was said."""

    INFORMATIONAL = "informational"
    """No operational claim is available. Reads are process evidence only."""

    MUTATION = "mutation"
    """One or more required state effects, plus communication requirements."""

    COMPOUND = "compound"
    """Several required effects with multiplicity and optional ordering."""


class ResultStatus(str, Enum):
    PASS = "pass"
    FAIL = "fail"
    UNKNOWN = "unknown"
    """Could not be scored. Never silently read as failure — see ``execute.py``."""

    NOT_APPLICABLE = "not_applicable"
    """This component makes no claim about this task.

    Distinct from ``UNKNOWN``, and the distinction is the point. An
    informational task has no operational requirement to meet, so reporting its
    operational result as unknown would suggest a measurement was attempted and
    failed. Nothing was attempted, because nothing was owed.
    """


class DeltaGroundTruthStatus(str, Enum):
    """What ``inferred_state_delta`` actually establishes, distinct from its content.

    An empty ``inferred_state_delta`` is ambiguous on its own: it could mean
    "compared before/after and confirmed nothing changed" or "could not align
    any reported field against a pre-action path at all." Those are different
    facts about the same empty dict, and collapsing them let a genuine
    cross-tool alignment gap (state paths are tool-prefixed, e.g.
    ``get_reservation_details.X.status`` vs ``cancel_reservation.X.status``,
    so a real mutation's before/after never share a path) read as a verified
    no-op instead of as "this cannot be measured yet."
    """

    MEASURED = "measured"
    """At least one field was compared before/after; inferred_state_delta
    holds exactly the confirmed changes (possibly zero, if genuinely none)."""

    UNAVAILABLE = "unavailable"
    """Reactions reported fields, but none could be path-matched against
    state_before -- typically a cross-tool entity-path mismatch. Whether
    anything changed is unknown, not "no." See unmatched_post_paths."""

    NOT_APPLICABLE = "not_applicable"
    """No reactions reported any comparable state paths at all (e.g. no tool
    observation, or a result with nothing structured to diff)."""


class ToolEffect(str, Enum):
    """Whether calling a tool can change the world."""

    READ = "read"
    """Returns information and mutates nothing."""

    WRITE = "write"
    """Mutates state. The only class that can carry operational success."""

    UNKNOWN = "unknown"
    """Not yet reviewed. Fails closed: never counted as either."""


class ToolEffectEntry(Contract):
    """One reviewed judgement about what a tool does."""

    tool: str
    effect: ToolEffect
    reviewed_by: str
    rationale: str = ""

    mutates_paths: tuple[str, ...] = ()
    """State-path patterns this tool may write, when review recorded them.

    Used by the transition validator to reject a proposed delta that touches an
    entity the called tool has no business touching.
    """

    @model_validator(mode="after")
    def write_review_is_named(self) -> ToolEffectEntry:
        if self.effect is not ToolEffect.UNKNOWN and not self.reviewed_by.strip():
            raise ValueError(f"classifying {self.tool!r} requires a named reviewer")
        if self.effect is ToolEffect.READ and self.mutates_paths:
            raise ValueError(f"read tool {self.tool!r} cannot declare mutated paths")
        return self


class ToolEffectCatalog(Contract):
    """Reviewed read/write classification for one toolset.

    Human-reviewed rather than inferred, and there is no naming fallback. The
    tau2 conversion dropped every tool ``description``, so the source declares
    nothing to derive a class from; a ``get_*`` prefix rule would have looked
    like it was reading metadata while actually guessing. An unclassified tool
    resolves to ``UNKNOWN`` and is counted toward neither side.
    """

    schema_version: int = 1
    catalog_id: str
    toolset_digest: str
    """Pins the toolset this was reviewed against, so a changed tool contract
    cannot silently inherit an old classification."""

    entries: tuple[ToolEffectEntry, ...]

    @model_validator(mode="after")
    def one_entry_per_tool(self) -> ToolEffectCatalog:
        names = [entry.tool for entry in self.entries]
        if len(names) != len(set(names)):
            raise ValueError("tool effect catalog classifies one tool twice")
        return self

    def effect_of(self, tool: str) -> ToolEffect:
        """Unreviewed tools fail closed rather than being guessed from the name."""
        for entry in self.entries:
            if entry.tool == tool:
                return entry.effect
        return ToolEffect.UNKNOWN

    def entry_for(self, tool: str) -> ToolEffectEntry | None:
        """The reviewed entry, or None when the tool is outside this catalog."""
        return next((entry for entry in self.entries if entry.tool == tool), None)

    def is_write(self, tool: str) -> bool:
        return self.effect_of(tool) is ToolEffect.WRITE


class MatchPolicy(Contract):
    """How required effects are matched against what a rollout actually did.

    Resolved once onto every binding rather than decided at execution time, so
    two runs of one verifier cannot disagree about what counted as a match.
    """

    mode: Literal["multiset", "sequence", "partial_order"] = "multiset"
    """Default is order-free. Ordering is a real constraint in some workflows
    and an accident of transcription in most, so it is enforced only where a
    reviewed contract declares it."""

    argument_match: Literal["exact", "subset", "reviewed"] = "subset"
    """``subset``: every argument the contract names must agree, and arguments
    it does not name are free. ``exact`` additionally forbids extra arguments.
    ``reviewed`` defers to per-effect rules a human wrote."""

    multiplicity_required: bool = True
    """Two required cancellations of different reservations need two distinct
    matching committed events. Cancelling one reservation twice satisfies one
    requirement, not both — each committed event is consumed at most once."""

    ordered_pairs: tuple[tuple[int, int], ...] = ()
    """Index pairs (before, after) for ``partial_order``."""

    @model_validator(mode="after")
    def ordering_matches_mode(self) -> MatchPolicy:
        if self.ordered_pairs and self.mode != "partial_order":
            raise ValueError("ordered pairs are only meaningful in partial_order mode")
        if self.mode == "partial_order" and not self.ordered_pairs:
            raise ValueError("partial_order mode must declare at least one ordered pair")
        return self


class ExpectedEffect(Contract):
    """One state change a task requires, as the sealed contract states it."""

    effect_id: str
    tool: str
    arguments: dict[str, Any] = Field(default_factory=dict)

    event_type: str | None = None
    """The committed event that evidences this effect, when review named one."""

    state_path: str | None = None
    expected_value: Any = None
    """A terminal state assertion, when the effect is checkable as state rather
    than only as an event."""

    rationale: str = ""


class ForbiddenEffect(Contract):
    """A state change that must NOT have happened.

    Carries refusal tasks, and guards every other shape: a mutation task that
    achieved its goal by also cancelling an unrelated reservation has not
    passed. Absence is genuinely checkable here — unlike a required effect, an
    empty ledger is positive evidence for a forbidden one.
    """

    effect_id: str
    tool: str | None = None
    arguments: dict[str, Any] = Field(default_factory=dict)
    event_type: str | None = None
    state_path: str | None = None
    must_remain: Any = None
    """The value this path must still hold at termination, when named."""

    rationale: str = ""

    @model_validator(mode="after")
    def names_something_to_forbid(self) -> ForbiddenEffect:
        if not (self.tool or self.event_type or self.state_path):
            raise ValueError("a forbidden effect must name a tool, event type, or state path")
        return self


class ProcessExpectation(Contract):
    """Something the agent was expected to *do*, carrying no success claim.

    Reads live here. That the candidate looked up the reservation is evidence
    about how it worked, not that the task was accomplished — and for the five
    read-only tasks in the target family, treating the lookup as the outcome
    would report a confident pass for having done nothing.
    """

    expectation_id: str
    tool: str
    arguments: dict[str, Any] = Field(default_factory=dict)
    rationale: str = ""


class CommunicationRequirement(Contract):
    """Something the agent had to convey, refuse, or confirm.

    Structurally separate from operational success because its authority is
    usually weaker: ``communicate_info`` is populated on 6 of 50 tau2 tasks, so
    most of these resolve to a natural-language assertion scored by a rubric,
    which enters as ``MODEL_JUDGMENT``. Averaging that into a state check would
    launder a judgement into an observation.
    """

    requirement_id: str
    assertion: str
    kind: Literal["communicate_info", "nl_assertion"] = "nl_assertion"
    expected_values: tuple[str, ...] = ()
    """Literal facts that must appear, for ``communicate_info``."""

    authority: EvidenceKind = EvidenceKind.MODEL_JUDGMENT

    @model_validator(mode="after")
    def literal_facts_are_named(self) -> CommunicationRequirement:
        if self.kind == "communicate_info" and not self.expected_values:
            raise ValueError("a communicate_info requirement must name the facts to convey")
        return self


class SealedSuccessContract(Contract):
    """What success means for one scenario, hidden from the candidate and the AWM.

    Sealed in the strong sense: the shape is selected from the *source* task
    contract before the rollout starts, and nothing either the candidate or the
    world model does may select or revise it. A simulator that could influence
    its own success criterion is the reward-hacking path the whole plane exists
    to close.
    """

    schema_version: int = 1
    contract_id: str
    source_task_id: str
    """The original task this was read from, e.g. a tau2 task id."""

    shape: SuccessShape
    required_effects: tuple[ExpectedEffect, ...] = ()
    forbidden_effects: tuple[ForbiddenEffect, ...] = ()
    process_expectations: tuple[ProcessExpectation, ...] = ()
    communication: tuple[CommunicationRequirement, ...] = ()
    match_policy: MatchPolicy = MatchPolicy()

    reward_basis: tuple[str, ...] = ()
    """Which components the source says its own grade rested on, e.g. DB and
    COMMUNICATE. Recorded so a binding cannot quietly drop a half the source
    considered required."""

    unbindable_reason: str | None = None
    """Set when the source contract could not be bound without an unreviewed
    interpretation. Such a scenario is verifier-unknown — never forced into the
    nearest shape, and never silently dropped from the denominator."""

    reviewed_by: str = ""

    @model_validator(mode="after")
    def shape_matches_content(self) -> SealedSuccessContract:
        if self.unbindable_reason:
            return self
        if self.shape is SuccessShape.REFUSAL:
            if self.required_effects:
                raise ValueError("a refusal contract cannot require a state effect")
            if not self.forbidden_effects:
                raise ValueError("a refusal contract must name what was forbidden")
        if self.shape is SuccessShape.INFORMATIONAL and self.required_effects:
            raise ValueError(
                "an informational contract claims no operational success; "
                "a required effect makes it a mutation"
            )
        if self.shape is SuccessShape.MUTATION and not self.required_effects:
            raise ValueError("a mutation contract must require at least one effect")
        if self.shape is SuccessShape.COMPOUND and len(self.required_effects) < 2:
            raise ValueError("a compound contract requires more than one effect")
        if self.shape is SuccessShape.INFORMATIONAL and not self.communication:
            raise ValueError(
                "an informational task is carried by what was communicated; "
                "without a requirement nothing would be scored at all"
            )
        return self

    @property
    def claims_operational_success(self) -> bool:
        """Whether an operational verdict is even available for this shape."""
        return self.shape in (SuccessShape.MUTATION, SuccessShape.COMPOUND, SuccessShape.REFUSAL)


class StateField(Contract):
    """One known fact about the simulated world, and where it came from."""

    path: str
    value: Any
    origin: WorldOrigin
    revealed_by_span_id: str | None = None
    """The authentic span that revealed it, for ``RECORDED`` fields."""

    revealed_at_step: int | None = None
    """The rollout step that committed it, for ``SIMULATED`` fields."""

    evidence_ids: tuple[str, ...] = ()

    @model_validator(mode="after")
    def origin_matches_provenance(self) -> StateField:
        if self.origin is WorldOrigin.RECORDED and self.revealed_at_step is not None:
            raise ValueError("a recorded field cannot have been committed by a rollout step")
        if self.origin is WorldOrigin.SIMULATED and self.revealed_by_span_id is not None:
            raise ValueError("a simulated field cannot cite an authentic span")
        return self


class ScenarioState(Contract):
    """The partial world a rollout knows about.

    Partial by construction. We hold no production database snapshot, so state
    is whatever the authentic prefix revealed plus whatever validated deltas the
    rollout committed. A path nobody has observed is *unknown*, not absent —
    the same rule ``execute.py`` applies to checks, for the same reason: absence
    of a fact is not evidence against it.
    """

    fields: tuple[StateField, ...] = ()

    def get(self, path: str) -> StateField | None:
        """None means unknown. Callers must not read that as a value."""
        for field in self.fields:
            if field.path == path:
                return field
        return None

    def known(self, path: str) -> bool:
        return self.get(path) is not None

    @property
    def simulated_paths(self) -> tuple[str, ...]:
        """Paths no longer backed by anything recorded.

        A verdict resting on one of these is simulation-conditioned, and the
        rollout report has to say so per verdict rather than per campaign.
        """
        return tuple(f.path for f in self.fields if f.origin is WorldOrigin.SIMULATED)


class HiddenUserProfile(Contract):
    """What the user knows, wants, and must not volunteer.

    Private to the environment. It feeds the user policy and the D23 disclosure
    fidelity gate; the candidate never sees any of it. Splitting known from
    unknown is what makes premature disclosure measurable at all: a simulated
    user that volunteers an identifier the real persona withheld has made the
    task easier, and pass@k would rise for a reason unrelated to the candidate.
    """

    reason_for_call: str = ""
    known_info: str = ""
    """Facts the user may disclose when appropriately asked."""

    unknown_info: str = ""
    """Facts the user does not have. Inventing them is a fidelity failure."""

    task_instructions: str = ""
    """How the user behaves under pressure: what to insist on, when to relent."""

    persona: str = ""

    known_facts: dict[str, Any] = Field(default_factory=dict)
    """Normalized fact id -> value, when compilation can recover structure."""

    unknown_fact_ids: tuple[str, ...] = ()
    """Fact ids the user is explicitly unable to provide."""


class Partition(str, Enum):
    FIT = "fit"
    HELD_OUT = "held_out"
    SEALED = "sealed"
    """Reserved tasks kept out of the corpus entirely. Opened once, for the
    final audit — never for retrieval, GEPA, prompt selection, or verifier
    iteration."""


class ScenarioKind(str, Enum):
    TASK_START = "task_start"
    MIDDLE_PREFIX = "middle_prefix"
    END_PREFIX = "end_prefix"


class PrefixStep(Contract):
    """One authentic turn replayed before the candidate takes over.

    Structured, not rendered: the candidate's own harness decides how to show a
    tool result, and a prompt-shaped string here would bake one harness's
    formatting into the scenario artifact.
    """

    role: Literal["system", "user", "assistant", "tool"]
    content: Any = None
    tool_name: str | None = None
    tool_call_id: str | None = None
    arguments: dict[str, Any] | None = None
    span_id: str | None = None
    error: bool = False


class CandidateView(Contract):
    """Exactly what a candidate is shown. Nothing private can reach this.

    A separate type rather than a method returning a dict, so that adding a
    private field to ``Scenario`` cannot silently start leaking: anything the
    candidate sees has to be given a home here deliberately.
    """

    scenario_id: str
    task: str
    system_policy: str | None
    offered_tools: tuple[dict[str, Any], ...]
    prefix: tuple[PrefixStep, ...]


class Scenario(Contract):
    """One compiled environment starting point, public and private halves together.

    The candidate never receives this object — only ``candidate_view()``.
    """

    schema_version: int = 1
    scenario_id: str
    kind: ScenarioKind

    task: str
    system_policy: str | None = None
    offered_tools: tuple[dict[str, Any], ...] = ()
    prefix: tuple[PrefixStep, ...] = ()
    """Authentic history through the cut point. Empty for ``task_start``."""

    initial_state: ScenarioState = ScenarioState()
    """Reconstructed from what the prefix revealed, and nothing else."""

    success_contract: SealedSuccessContract
    hidden_user: HiddenUserProfile = HiddenUserProfile()

    source_trace_id: str
    source_task_id: str
    lineage_id: str | None = None
    family_id: str
    partition: Partition
    cut_span_id: str | None = None
    """The authentic span the prefix ends at, for middle and end prefixes."""

    retrieval_excluded_trace_ids: tuple[str, ...] = ()
    """Traces this scenario's rollout may never retrieve from.

    Its own trace and its whole lineage group, at minimum. Asserted at query
    time as well as build time: a shared index is exactly the thing that
    quietly stops being partitioned.
    """

    @model_validator(mode="after")
    def prefix_matches_kind(self) -> Scenario:
        if self.kind is ScenarioKind.TASK_START and self.prefix:
            raise ValueError("a task-start scenario shows no authentic history")
        if self.kind is not ScenarioKind.TASK_START and not self.prefix:
            raise ValueError(f"a {self.kind.value} scenario requires an authentic prefix")
        if self.kind is not ScenarioKind.TASK_START and not self.cut_span_id:
            raise ValueError(f"a {self.kind.value} scenario must record where it cut")
        return self

    @model_validator(mode="after")
    def excludes_its_own_source(self) -> Scenario:
        if self.source_trace_id not in self.retrieval_excluded_trace_ids:
            raise ValueError(
                "a scenario must exclude its own trace from retrieval; otherwise the "
                "world model can copy the real next observation and fidelity measures nothing"
            )
        return self

    @model_validator(mode="after")
    def prefix_state_is_recorded(self) -> Scenario:
        """Initial state comes from the prefix, or from a reviewer's assertion.

        Never from the simulator. A scenario that started from invented state
        would make every verdict built on it simulation-conditioned before the
        candidate had acted once.
        """
        simulated = [
            f.path for f in self.initial_state.fields if f.origin is not WorldOrigin.RECORDED
        ]
        if simulated:
            raise ValueError(
                f"initial state must come from the authentic prefix; {simulated} are not recorded"
            )
        return self

    def candidate_view(self) -> CandidateView:
        """The only sanctioned way to build what a candidate is shown."""
        return CandidateView(
            scenario_id=self.scenario_id,
            task=self.task,
            system_policy=self.system_policy,
            offered_tools=self.offered_tools,
            prefix=self.prefix,
        )


class ActionCall(Contract):
    """One tool call inside an action.

    An action is not one call. 54 actions in the tau2 corpus carry several — one
    carries ten — and the ingest adapter splits them into consecutive model
    spans. Reading each span as its own turn fragments a parallel batch into
    pseudo-sequential turns and pairs each call with whichever result happened
    to follow it, which is not necessarily its own.
    """

    call_id: str | None = None
    tool: str
    arguments: dict[str, Any] = Field(default_factory=dict)


class GroundingObservation(Contract):
    """One thing that reacted to an action, with its pairing preserved.

    ``tool_call_id`` is what joins a result back to the call it answers. Without
    it a batch of parallel calls and their results is an unordered bag, and the
    simulator would learn to emit results in an order nothing guarantees.
    """

    role: Literal["tool", "user"]
    content: Any = None
    tool_name: str | None = None
    tool_call_id: str | None = None
    span_id: str | None = None
    error: bool = False


class GroundingTransition(Contract):
    """One real (action -> next observation) example, losslessly.

    The AWM's view of a turn, deliberately distinct from PR #44's ``Turn``,
    which is the *judge's* view. That one clips the action to 1600 characters
    and each reaction to 1200 and renders structured results to strings — right
    for a judge that only has to say +1/0/-1, and wrong twice over here: a
    truncated JSON result teaches the simulator to emit truncated JSON, and a
    fidelity comparison needs the real structured payload to diff fields
    against. Clipping is a rendering concern, applied against a context budget
    when a prompt is built, never at extraction.

    The span-boundary rule is shared with ``Turn`` and is correct: a model span
    opens an action, the tool results and user messages before the next model
    span are its reaction, and a trailing action with no reaction is unobserved.
    """

    schema_version: int = 1
    transition_id: str
    trace_id: str
    lineage_id: str | None = None
    family_id: str
    turn_index: int
    """Joins to PR #44's ``Turn.index`` over the same span boundary."""

    task_context: str = ""
    success_shape: SuccessShape | None = None
    """The shape of the task this transition came from, when its source task was
    bound. Retrieval filters on it *before* ranking: an over-merged family can
    otherwise offer a booking mutation as an analogous success to a scenario
    whose whole point was declining. None where the source task was never
    bound, which restricts the transition to informational use."""

    history_before: tuple[PrefixStep, ...] = ()
    """Unclipped. Rendering decides what fits in a prompt, not extraction."""

    state_before: ScenarioState = ScenarioState()

    action_span_id: str
    """The first span of this action. A batched action spans several."""

    action_span_ids: tuple[str, ...] = ()
    action_content: Any = None
    action_calls: tuple[ActionCall, ...] = ()
    """Every call the action made, in order. Empty for plain speech."""

    observations: tuple[GroundingObservation, ...] = ()
    """Every reaction, in order, each paired to the call it answers."""

    inferred_state_delta: dict[str, Any] = Field(default_factory=dict)
    """Confirmed mutations only -- see DeltaGroundTruthStatus before trusting
    an empty dict here as "verified no change." Check delta_ground_truth_status
    first."""

    delta_ground_truth_status: DeltaGroundTruthStatus = DeltaGroundTruthStatus.NOT_APPLICABLE
    unmatched_post_paths: tuple[str, ...] = ()
    """Post-action paths that were reported but could not be aligned against
    any state_before path (status UNAVAILABLE). Kept for a future reviewed
    tau2 path canonicalizer to consume -- never guessed at automatically."""

    observed: bool = True
    """False when nothing followed the action.

    Excluded from the grounding index and from fidelity scoring — silence is
    not an observation and cannot teach one — but kept, because how much of a
    family's tail is unobserved is itself a limitation the report must carry.
    """

    stripped_markers: tuple[str, ...] = ()
    """Control markers removed for the AWM-facing view, e.g. ``###TRANSFER###``.

    Recorded rather than silently dropped: a fidelity comparison must not be
    penalised for a difference that was only scaffolding, and an AWM shown the
    marker would learn to emit it on episodes that do not escalate.
    """

    @model_validator(mode="after")
    def observed_matches_its_observations(self) -> GroundingTransition:
        if self.observed and not self.observations:
            raise ValueError("an observed transition must carry what reacted")
        if not self.observed and self.observations:
            raise ValueError("an unobserved transition cannot carry an observation")
        return self

    @property
    def reaction_role(self) -> str:
        """``tool``, ``user``, ``mixed`` or ``none``. Derived, never stored."""
        roles = {observation.role for observation in self.observations}
        if not roles:
            return "none"
        return roles.pop() if len(roles) == 1 else "mixed"

    @property
    def action_tool(self) -> str | None:
        """The single tool called, when exactly one was. None for speech or a batch."""
        return self.action_calls[0].tool if len(self.action_calls) == 1 else None


class ClaimOrigin(Contract):
    """Where one verifier input came from, carried beside its authority."""

    world: WorldOrigin
    authority: EvidenceKind = EvidenceKind.OBSERVED_TRACE
    evidence_ids: tuple[str, ...] = ()
    step_index: int | None = None


class VerifierInputClaim(Contract):
    """One fact offered to a check, from a recorded episode or a rollout.

    The shared surface D13 calls for. It carries the same claim names
    ``analyze/outcomes.py`` emits — ``final_state_field``,
    ``initial_state_field``, ``span_error``, ``episode_span_count`` — so the
    existing operator semantics execute unchanged, which is the only basis on
    which a historical score and a rollout score are comparable at all.

    ``origin.world`` is what makes a verdict simulation-conditioned, and it is
    per claim rather than per rollout: a verdict resting entirely on recorded
    prefix state is not conditioned on the simulator even inside a simulated
    rollout.
    """

    claim: str
    value: Any
    origin: ClaimOrigin
    detail: str | None = None


class ComponentResult(Contract):
    """One half of a verdict, with its own authority and its own reasons."""

    status: ResultStatus
    detail: str = ""
    authority: EvidenceKind | None = None
    checked: tuple[str, ...] = ()
    unmet: tuple[str, ...] = ()
    simulated_inputs: int = 0
    """How many claims behind this component were simulator-produced."""

    @model_validator(mode="after")
    def not_applicable_is_empty(self) -> ComponentResult:
        if self.status is ResultStatus.NOT_APPLICABLE and self.unmet:
            raise ValueError("a component that makes no claim cannot report unmet requirements")
        return self


class VerifierBinding(Contract):
    """A reviewed template plus one scenario's sealed contract, resolved.

    The template says *how* a shape is checked; the sealed contract supplies the
    expected values. Neither the candidate nor the AWM may supply or revise
    either half — that separation is what stops a simulator from writing its own
    success criterion.
    """

    schema_version: int = 1
    binding_id: str
    scenario_id: str
    contract_id: str
    shape: SuccessShape
    template_id: str
    """The reviewed sub-shape template this was bound from."""

    reviewed_verifier_id: str | None = None
    """The promoted verifier carrying the deterministic checks, once one exists.

    None while Gate 0 is open. A binding without it can be executed for
    development, and its results are development-only.
    """

    match_policy: MatchPolicy = MatchPolicy()
    """Resolved here, never re-derived at execution time."""

    required_reward_basis: tuple[str, ...] = ()

    @model_validator(mode="after")
    def promoted_binding_names_its_verifier(self) -> VerifierBinding:
        if self.shape is SuccessShape.INFORMATIONAL and self.match_policy.ordered_pairs:
            raise ValueError("an informational binding has no effects to order")
        return self


class TerminationReason(str, Enum):
    CANDIDATE_COMPLETED = "candidate_completed"
    USER_TERMINATED = "user_terminated"
    TERMINAL_EVENT = "terminal_event"
    STEP_LIMIT = "step_limit"
    TOKEN_LIMIT = "token_limit"
    TIME_LIMIT = "time_limit"
    ACTION_LOOP = "action_loop"
    UNAVAILABLE_TOOL = "unavailable_tool"
    """The candidate called a tool absent from its offered toolset."""
    INVALID_CANDIDATE_ACTION = "invalid_candidate_action"
    """A candidate tool call violated the offered argument schema."""
    INVALID_TRANSITION = "invalid_transition"
    UNSUPPORTED_ACTION = "unsupported_action"
    AWM_ABSTAINED = "awm_abstained"

    @property
    def invalidates_rollout(self) -> bool:
        """Whether the rollout can carry a capability verdict at all.

        An abstention is the environment declining to answer, not the candidate
        failing. Scoring it as a failure would charge the candidate for the
        simulator's ignorance, and scoring it as a pass would reward walking
        off the supported manifold. It leaves the denominator, and the rate is
        reported on its own.
        """
        return self in (
            TerminationReason.UNSUPPORTED_ACTION,
            TerminationReason.AWM_ABSTAINED,
            TerminationReason.INVALID_TRANSITION,
        )

    @property
    def is_candidate_failure(self) -> bool:
        return self in (
            TerminationReason.STEP_LIMIT,
            TerminationReason.TOKEN_LIMIT,
            TerminationReason.TIME_LIMIT,
            TerminationReason.ACTION_LOOP,
            TerminationReason.UNAVAILABLE_TOOL,
            TerminationReason.INVALID_CANDIDATE_ACTION,
        )


class SupportLevel(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    NONE = "none"
    """No relevant evidence. The AWM must abstain rather than invent."""


class SupportPolicy(Contract):
    """Reviewed calibration deciding when simulated claims may be committed."""

    schema_version: int = 1
    policy_id: str
    tool_minimum: SupportLevel
    reviewed_by: str
    calibration_report_id: str

    @model_validator(mode="after")
    def review_and_calibration_are_named(self) -> SupportPolicy:
        if not self.reviewed_by.strip() or not self.calibration_report_id.strip():
            raise ValueError("a support policy requires a reviewer and calibration report")
        if self.tool_minimum is SupportLevel.NONE:
            raise ValueError("a support policy cannot commit unsupported transitions")
        return self


class EntityRef(Contract):
    """A domain entity identified independently of which tool named it.

    ``get_reservation_details(Q69X3R)`` and ``cancel_reservation(Q69X3R)``
    must resolve to the same ``reservation:Q69X3R`` -- tool-namespacing the
    key (``f"{tool}.{id}"``) breaks that identity and silently reproduces the
    cross-tool state-path problem ``inferred_state_delta`` already hit
    (I38/D77). The tool describes an operation; it is never part of what
    entity a call refers to.
    """

    kind: str
    id: str

    @property
    def key(self) -> str:
        return f"{self.kind}:{self.id}"


class GroundingKind(str, Enum):
    """Reporting summary of a ``CallGroundingAssessment``. Never the scoring input.

    Two independent questions collapse into one label here only for display:
    whether a call's exact required values are identifiable, and whether its
    behavior (shape/success/error semantics) is evidenced at all. A
    same-tool-different-entity retrieval hit proves the second without ever
    proving the first (I39) -- scoring code must read the two booleans on
    ``CallGroundingAssessment`` directly, not branch on this enum.
    """

    EXACT_ENTITY_FACT = "exact_entity_fact"
    """The exact record is already known -- read from state_before or from
    retrieved evidence about this same entity. A record-materialization read
    (get_user_details, get_reservation_details) reports this record; it does
    not derive it."""
    DERIVABLE_FROM_STATE = "derivable_from_state"
    """Reserved for a mutation whose post-state is a transformation of known
    pre-state plus supported behavior (e.g. cancellation). Not emitted by the
    current record-materialization classifier, which covers only reads."""
    BEHAVIORAL_ANALOGY = "behavioral_analogy"
    """behavior_supported only -- same tool, different entity. Cannot license a
    field-value fidelity claim, only a shape/status claim."""
    UNSUPPORTED = "unsupported"
    """Neither dimension is evidenced."""
    UNAVAILABLE = "unavailable"
    """This call's tool/shape is outside what the classifier covers (writes,
    search, transfer, booking, ...) or it is part of a mixed-grounding batch.
    Distinct from UNSUPPORTED: this is "we did not assess it," not "we
    assessed it and found nothing." Never used for abstention calibration."""


class CallGroundingAssessment(Contract):
    """What one tool call's required facts and behavior are backed by.

    Grounding is a per-call question, not a per-transition one (D39/D53/D70):
    a batch pairing a known-entity call with an unknown-entity call must not
    let one call's evidence license a claim about the other. ``call_id``
    correlates back to the ``ActionCall`` and to the recorded
    ``GroundingObservation.tool_call_id`` that answered it.
    """

    call_id: str | None = None
    tool: str
    target_entities: tuple[EntityRef, ...] = ()
    required_fact_paths: tuple[str, ...] = ()
    """Field paths this call's recorded result actually populated. Only
    meaningful for held-out fidelity scoring, where the recorded result is
    known to derive demand from -- never shown to the predictor being scored."""
    identifiable_fact_paths: tuple[str, ...] = ()
    missing_fact_paths: tuple[str, ...] = ()
    exact_fact_evidence_ids: tuple[str, ...] = ()
    behavioral_evidence_ids: tuple[str, ...] = ()
    values_identifiable: bool = False
    """True only if every required fact path was identifiable from state_before
    or from retrieved evidence about the *same* target entity."""
    behavior_supported: bool = False
    """True if retrieval found evidence of how this tool behaves, regardless
    of which entity it concerned."""
    kind: GroundingKind = GroundingKind.UNAVAILABLE


class GroundingAssessment(Contract):
    """Per-call grounding for one transition's action.

    Deliberately not reduced to one transition-level verdict: a batch mixing
    an identifiable call with an unidentifiable one has no single correct
    abstain/answer label, and collapsing to one would either license the
    unidentifiable call or wrongly penalize the identifiable one.
    """

    calls: tuple[CallGroundingAssessment, ...] = ()

    @property
    def single_call(self) -> CallGroundingAssessment | None:
        return self.calls[0] if len(self.calls) == 1 else None

    @property
    def values_identifiable(self) -> bool | None:
        """None for any batch, or when the one call was never assessed.

        Proposal-wide abstention cannot be scored from per-call grounding for
        a batch: two calls both being unidentifiable does not make a whole-
        transition abstention "correct" in any sense the runtime's
        all-or-nothing abstain flag can represent. Restricted to single-call
        transitions until an explicit per-call unresolved status exists."""
        if len(self.calls) != 1:
            return None
        call = self.calls[0]
        return None if call.kind is GroundingKind.UNAVAILABLE else call.values_identifiable


class RolloutStep(Contract):
    """One candidate action and the environment's response to it.

    An action may carry several calls, as recorded actions do. ``calls`` is the
    representation; ``action_tool``/``action_arguments`` are conveniences for
    the single-call case and are None/empty for a batch, so a caller that reads
    only them cannot silently score one call of several.
    """

    index: int
    calls: tuple[ActionCall, ...] = ()
    action_content: Any = None

    responder: Literal["tool_world", "user_policy", "none"] = "none"
    observation: Any = None
    committed_delta: dict[str, Any] = Field(default_factory=dict)
    events: tuple[dict[str, Any], ...] = ()
    output_schema_validation: dict[
        str, Literal["validated", "unavailable", "invalid"]
    ] = Field(
        default_factory=dict
    )
    """Per-call result validation. Missing is not silently read as validated.

    ``invalid`` is retained on a rejected step so persisted campaigns explain
    why the validator refused to commit the proposed transition.
    """

    committed_call_ids: tuple[str, ...] = ()
    """Which calls of this step actually committed something.

    A batch is not all-or-nothing. ``cancel(A)`` succeeding and ``cancel(B)``
    failing in one action must not satisfy two required cancellations, and
    without per-call identity the step's single delta makes every call in it
    look committed.
    """

    executed_call_ids: tuple[str, ...] = ()
    """Calls that reached the tool at all, committed or not.

    A forbidden execution that emitted no delta still happened, and checking
    only committed effects would let it disappear.
    """
    terminal: bool = False

    world: WorldOrigin = WorldOrigin.SIMULATED
    support: SupportLevel = SupportLevel.NONE
    retrieved_transition_ids: tuple[str, ...] = ()
    validator_rejections: tuple[str, ...] = ()
    abstained: bool = False
    disclosed_facts: tuple[str, ...] = ()
    """What the user policy revealed this step, for the D23 disclosure gate."""

    @model_validator(mode="after")
    def abstention_commits_nothing(self) -> RolloutStep:
        if self.abstained and (self.committed_delta or self.events):
            raise ValueError("an abstained step cannot commit state or emit events")
        return self

    @property
    def action_tool(self) -> str | None:
        """The single tool called, or None for speech or a batch."""
        return self.calls[0].tool if len(self.calls) == 1 else None

    @property
    def action_arguments(self) -> dict[str, Any]:
        return dict(self.calls[0].arguments) if len(self.calls) == 1 else {}


class RolloutResult(Contract):
    """One complete candidate attempt against one scenario.

    The three component results are never averaged. ``overall`` fails closed:
    a required component that could not be scored makes the whole verdict
    unknown, matching the fail-closed composition used throughout verification.
    """

    schema_version: int = 1
    rollout_id: str
    scenario_id: str
    binding_id: str
    candidate_id: str
    seed: int

    steps: tuple[RolloutStep, ...] = ()
    final_state: ScenarioState = ScenarioState()
    terminated_by: TerminationReason

    operational_result: ComponentResult
    process_result: ComponentResult
    communication_result: ComponentResult
    overall: ResultStatus

    simulation_conditioned: bool = True
    """False only when every claim behind the verdict was recorded.

    Reachable in principle for an end-prefix scenario the candidate completed
    without needing a simulated transition; never assumed.
    """

    tool_awm_version: str = ""
    user_policy_version: str = ""
    retrieval_index_version: str = ""
    scenario_set_version: str = ""
    """Every full-rollout number is conditioned on all four. Pinned on the
    result rather than on the campaign, because a campaign that swapped a
    component mid-run would otherwise report one version for two populations."""

    @model_validator(mode="after")
    def overall_fails_closed(self) -> RolloutResult:
        components = (self.operational_result, self.communication_result)
        if any(c.status is ResultStatus.FAIL for c in components):
            if self.overall is not ResultStatus.FAIL:
                raise ValueError("a failed required component must fail the overall verdict")
            return self
        if any(c.status is ResultStatus.UNKNOWN for c in components):
            if self.overall is not ResultStatus.UNKNOWN:
                raise ValueError(
                    "an unknown required component makes the overall verdict unknown, never a pass"
                )
            return self
        if self.overall is ResultStatus.PASS:
            scored = [
                c
                for c in components
                if c.status not in (ResultStatus.NOT_APPLICABLE, ResultStatus.UNKNOWN)
            ]
            if not scored:
                raise ValueError("an overall pass requires at least one component that passed")
        return self

    @model_validator(mode="after")
    def invalid_rollout_claims_nothing(self) -> RolloutResult:
        if self.terminated_by.invalidates_rollout and self.overall is not ResultStatus.UNKNOWN:
            raise ValueError(
                f"a rollout terminated by {self.terminated_by.value} left the denominator; "
                "it cannot report a pass or a failure"
            )
        return self
